name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tags to execute'
        required: false
        default: ''
        type: choice
        options:
          - '@smoke'
          - '@regression'
          - '@e2e'
          - '@performance'
          - '@web'
          - '@api'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Opt into Node.js 24

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.tag }}" != "" ]; then
            npx playwright test --grep "${{ github.event.inputs.tag }}"
          else
            npx playwright test
          fi
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-html-report
          path: playwright-report/
